#!/usr/bin/env bash

usage() {
  local name="$(basename "$0")"
  echo -e "Usage $name:\n\t$name <mod url>"
  echo -e "\t$name <mod ID>"
  echo -e "\t$name <mod Name>"
}

file="$1"

if [[ -z "$file" ]]; then
  usage
  exit 1
fi

names=()

for name in "$@"; do
  packwiz modrinth add "$name"
  names+=("$name")
done
git add .
git commit -qm "Added '$names'"
echo -e "\033[93mDon't forget to push !\033[0m"
