#!/usr/bin/env bash

usage() {
  local name="$(basename "$0")"
  echo -e "Usage $name:"
  echo -e "\t$name <mod Name>"
}

file="$1"

if [[ -z "$file" ]]; then
  usage
  exit 1
fi

for file_name in $(find . -type f -iname "*$file*"); do
  name=$(basename $file_name)
  echo "Found: ${name//\.toml/}"
done
