name = "Mato"
author = "MathChameleon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6310af7bb1c1d4404bb36a6bd470b699ce25e4fafa942d75e5fbb417110e474"

[versions]
fabric = "0.18.5"
minecraft = "1.21.11"
