name = "Mato"
author = "MathChameleon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55c92576162ff37ef11307997338f42946d60b88894d83ea59f711c6d149de5b"

[versions]
fabric = "0.18.5"
minecraft = "1.21.11"
