name = "Mato"
author = "MathChameleon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6314e8bbda88f0414bed5a5b690f50660cf57279a0f692dfa30d032d9bf3a0a9"

[versions]
fabric = "0.18.5"
minecraft = "1.21.11"
