#!/usr/bin/env bash

usage() {
  local name="$(basename "$0")"
  echo -e "Usage $name:\n\t$name <mod YAML name>"
}

file="$1"

if [[ -z "$file" ]]; then
  usage
  exit 1
fi

names=()

for name in "$@"; do
  packwiz remove "$name"
  if [ ! $? -eq 0 ]; then
    continue
  fi

  names+=("$name")
done
git add .
git commit -qm "Removed '$names'"
echo -e "\033[93mDon't forget to push !\033[0m"
